import { cpSync, mkdirSync, existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { PERSONA_IDS, buildTakeawayPersona, PERSONA_REVISION } from "../shared/dialogue.js";
import { assertOptimizedImages, publicAssetFilter, removeGeneratedPngCopies } from "./public-images.js";
import { applyShareMetadata, buildCanonicalUrl } from "./share-metadata.js";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const output = join(root, "public");
// Validate before writing any build outputs. No inferred preview/deployment URL.
const canonical = buildCanonicalUrl(process.env.APP_URL || "");
const allowed = ["assets", "css", "js", "index.html", "legal.html", "terms.html", "privacy.html"];
// Refuse an unexpected output tree instead of deleting files or publishing it.
if (existsSync(output) && readdirSync(output).some(name => !allowed.includes(name))) {
  throw new Error("Unexpected file in public/: inspect the generated directory before building.");
}
// A deliberately public subset, generated from the one authored persona source.
// Do not publish shared/dialogue.js or the server's structured-output contract.
const takeaway = Object.fromEntries(PERSONA_IDS.map(id => [id, buildTakeawayPersona(id)]));
const takeawayModule = `// Generated by scripts/build-public.js from shared/dialogue.js. Do not edit.\n`
  + `// Public persona instructions only; no user data or provider output contract.\n`
  + `export const TAKEAWAY_VERSION = 2;\n`
  + `export const TAKEAWAY_REVISION = ${JSON.stringify(PERSONA_REVISION)};\n`
  + `export const TAKEAWAY_PERSONAS = Object.freeze(Object.fromEntries(Object.entries(${JSON.stringify(takeaway, null, 2)})\n`
  + `  .map(([id, persona]) => [id, Object.freeze(persona)])));\n`;
writeFileSync(join(root, "js", "data", "takeawayPersonas.js"), takeawayModule, "utf8");
assertOptimizedImages(root);
mkdirSync(output, { recursive: true });
const removed = removeGeneratedPngCopies(root, output);
for (const name of allowed) cpSync(join(root, name), join(output, name), {
  recursive: true,
  ...(name === "assets" ? { filter: publicAssetFilter(root) } : {}),
});
writeFileSync(join(output, "index.html"), applyShareMetadata(readFileSync(join(root, "index.html"), "utf8"), canonical), "utf8");
console.log(canonical ? "Static X/Open Graph card configured with APP_URL." : "APP_URL is not public: canonical/image URLs and public sharing controls are omitted.");
if (removed) console.log(`Removed ${removed} verified duplicate PNGs from public only; source originals are preserved.`);
console.log("Public build: UI assets only; API source, SQL, credentials and tests are not static files.");
